# Generated by Django 4.2.1 on 2023-05-23 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post1', models.CharField(help_text='Nombre-Tour (Maximo 32#)', max_length=32, verbose_name='Nombre:')),
                ('post2', models.CharField(help_text='Nombre-Tour (Maximo 32#)', max_length=32, verbose_name='Nombre:')),
                ('post1_banner', models.ImageField(blank=True, help_text='Width 720px x Height 730px', max_length=128, null=True, upload_to='uploads/post/', verbose_name='Imagen-1')),
                ('post2_banner', models.ImageField(blank=True, help_text='Width 720px x Height 730px', max_length=128, null=True, upload_to='uploads/post/', verbose_name='Imagen-2')),
                ('IsActive', models.BooleanField(default=True, verbose_name='¿Activo?')),
            ],
            options={
                'verbose_name': 'Configuracion',
                'verbose_name_plural': 'Configuraciones',
            },
        ),
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre-Tour (Maximo 32#)', max_length=32, verbose_name='Nombre:')),
                ('banner', models.ImageField(blank=True, help_text='Width 1920px x Height 2190px', max_length=128, null=True, upload_to='uploads/tours/', verbose_name='Imagen')),
                ('location', models.CharField(help_text='Ubicacion (Maximo 32#)', max_length=32, verbose_name='Localizacion:')),
                ('date', models.DateField(default=datetime.date.today, help_text='Fecha de Inicio del Tour', verbose_name='Fecha:')),
                ('description', models.TextField(blank=True, help_text='Descripcion-Tour (Maximo 128#)', max_length=256, null=True, verbose_name='Comentarios')),
                ('price', models.PositiveBigIntegerField(blank=True, default=0, help_text='$ ($COP)', verbose_name='Valor')),
                ('online', models.BooleanField(default=True, verbose_name='¿Activo?')),
            ],
            options={
                'verbose_name': 'Tour',
                'verbose_name_plural': 'Tours',
            },
        ),
    ]
