# Generated by Django 4.2.1 on 2023-05-23 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_alter_tours_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='date',
            field=models.DateField(default=datetime.date.today, help_text='Fecha de Inicio del Tour', verbose_name='Fecha:'),
        ),
    ]
