# Generated by Django 4.2.1 on 2023-05-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_alter_tours_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Setting', 'verbose_name_plural': 'Settings'},
        ),
        migrations.AddField(
            model_name='settings',
            name='post3',
            field=models.CharField(default=0, help_text='Nombre-Tour (Maximo 32#)', max_length=32, verbose_name='Nombre:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='post3_banner',
            field=models.ImageField(blank=True, help_text='Width 720px x Height 730px', max_length=128, null=True, upload_to='uploads/post/', verbose_name='Imagen-2'),
        ),
    ]
